site:
  title: Blog Local Preview
  start_page: blog::index.adoc
content:
  sources:
   - url: .
     branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  fetch: true
  cache_dir: ./cache
