= Statement of Purpose

*Maria Zhirko, M.Sc. Applicant*

[IMPORTANT]
====
This is an actual SOP reviewed by the admissions committee that I have decided to make public. It serves as a cautionary example of how not to write a letter to admissions, while also showcasing my personal views and achievements. For privacy reasons, I have redacted the most personal parts of the letter, but their exclusion has not impacted the structure or overall message of the document.

I urge readers not to copy and paste the following text, as it contains my personal experiences and opinions. While I support ecological reusability, the contents of this document are not meant for duplication.
==== 

Utilizing artificial intelligence is becoming an increasingly popular solution for treating widespread complex diseases. Using novel statistical learning approaches to impove the performance of existing clinical tools is the new forefront for more resilient and affordable healthcare systems.I am looking for a program that combines computational methods, machine learning, and medical applications to further my professional development and gain academic exposure to relevant coursework in medicine to pursue research at the intersection of the two fields. |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||. With my previous training in AI and research experience in the medical field, I am confident that this program will provide me with the knowledge and skills to excel. 

My path toward computer science and interest in health began in middle school. In 2015, interested in the Internet of Things, I created a device that tracked and stored air contamination
data to study the effect of pollutants on human health. With this work, I participated in and won several nationwide student research conferences and competitions, |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||. Subsequently, I was admitted into Belarusian State University of Informatics and Radioelectronics. There, I was eager to gain a deep understanding of how to represent, integrate, and use knowledge and data in a structured and machine-readable way and joined a lab that developed an open-source system for solving information organization, retrieval, and decision-making tasks using semantic networks. As a research assistant, I participated in the development of a system in the bibliography domain and later became a supervisor of the project, mentoring undergraduate students and reporting to the principal investigator.

While I was still at the university, my family members started having health problems: ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||. Finding a way to help them was a challenging problem. Having looked into the major challenges my grandparents and other patients face, I learned that the issues in scalability and access in healthcare often hinder medical knowledge itself. Over the centuries, medicine has accumulated a great amount of expertise which is currently not used to the best of its potential. The secrecy behind the medical data, its scarcity, and propriety of equipment, lack of in-depth pattern analysis, and disregard for secondary factors contribute to the inaccessibility of medicine.I believe that novel statistical learning approaches open wide opportunities to create open-source, automated systems for better medical decision-making and improve healthcare systems.

This understanding spurred me to look for research opportunities in the field of medical technology and artificial intelligence. Together with a groupmate, I published a study on the segmentation of brain tumor multi-parametric MRI scans. We chose a Dense V-Net architecture as the basis for solving the problem because of its great performance segmenting CT images of organs, and the similarity between MRI scanning and organ segmentation tasks. We modified its architecture and tackled the issue of “catastrophic inference” - a possibility of forgetting previously seen feature maps. We also included the ability to process the input at different resolutions by merging feature maps from several layers of the network. As a result, our model was less likely to miss small tumors.

After graduation I developed another medical project that allows one to determine a disease by the symptoms of a sick person, as well as to select medicines and appropriate treatment recommendations. The objective was to create an interactive environment to raise medical professionals’ attention to the problem of data collection in public health and create a centralized platform for collecting accessible data related to electronic health records to serve as the basis for open-source models. The study focused on efficient ways to implement the proposed recommender system and to fulfill all the main goals in terms of achieving a competitive advantage with the research carried out and serving as a launching point for future research in the field of medical exams. ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| I am confident that scaling such tools could provide great help to people and continue actively working on the development of a production-ready version. I am interested in discussing my findings |||||||||||||||||||||[this will] undoubtedly help me to refine results and deliver higher-quality service.

Working as a machine learning engineer at Qulix Systems helped me to achieve an appropriate level of knowledge to work on more advanced projects. As one of the first trained machine learning engineers at the company, I was tasked with expanding the company’s research department and had an opportunity to propose and organize new projects, actively communicate with the client, and develop new product features. My university thesis, conducted in parallel with my first internship there, focused on developing investment analytics tools with natural language processing modules. |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||.

In addition to my interests in technical innovation, I am passionate about expanding the social impact of my work as a researcher and solving broader issues of technology access and development. In 2021, I was a part of the team organizing the DEBRA International Medical Congress, where I hired and coordinated a team of international volunteers to support the event. In the summer of 2022, I interned at the United Nations Development Coordination Office where I provided a meaningful contribution to Ukraine by working as a data scientist. ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

With a diverse experience in medical research and social impact, I am convinced that novel information technologies have the potential to improve access and quality of medicine worldwide and enhance sustainable development. I am excited to continue my path as a student and a researcher, defining my mission in the following respects:

- Systematize and develop models to identify diseases and recommend treatments based on symptoms;
- Introduce the principles and culture of open source in the management of such models;
- Involve medical professionals in the community by giving them an accessible tool to work with models;
- Create tools to collect data on medical histories without personalizing them.

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||. By participating in these programs, I hope to acquire the skills and knowledge to address the learning gap in medical skills that I did not have a chance to cover in Belarus due to a highly compartmentalized academic structure. Ultimately,my goal is to use my education to create a more open and innovative healthcare system and research in future democratic Belarus.